# Generated by Django 3.2 on 2021-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientname',
            old_name='name',
            new_name='singular',
        ),
        migrations.AddField(
            model_name='ingredientname',
            name='plural',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
