# Generated by Django 3.2 on 2021-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredientname_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientname',
            name='plural',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
