# Generated by Django 3.2 on 2021-08-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredientname_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownIngredientNamesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_names', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
