# Generated by Django 3.2 on 2021-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_unknowningredientnamesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownIngredientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnknownIngredientNamesReport',
        ),
    ]
