# Generated by Django 3.2 on 2021-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20210815_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientname',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
