# Generated by Django 3.2 on 2021-04-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_city_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='city',
        ),
    ]
