# Generated by Django 3.2 on 2021-07-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_location_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='private_location',
        ),
    ]
