# Generated by Django 3.2 on 2021-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientname',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipeedition',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_editions', to='ingredients.Ingredient'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientName',
        ),
    ]
