# Generated by Django 3.2 on 2021-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20210419_0703'),
        ('recipes', '0002_auto_20210418_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeedition',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='ingredients.Ingredient'),
        ),
    ]
