# Generated by Django 3.2 on 2021-04-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeedition',
            name='ingredient_section',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lines', to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
