# Generated by Django 3.2 on 2021-07-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientline_recipe_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videourl',
            name='recipe_edition',
        ),
        migrations.RemoveField(
            model_name='ingredientline',
            name='recipe_edition',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lines', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_section',
            field=models.TextField(default='01-01-2021', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='No title', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeEdition',
        ),
        migrations.DeleteModel(
            name='VideoURL',
        ),
    ]
