# Generated by Django 3.2 on 2021-08-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_preparation_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientline',
            name='text',
            field=models.TextField(),
        ),
    ]
