# Generated by Django 3.2 on 2021-07-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
