# Generated by Django 3.2 on 2021-07-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210721_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
